import { useEffect, useMemo, useState } from 'react';
import { Boxes, CircleDollarSign, LayoutDashboard, LogOut, Plus, Server, Settings, Ticket, Wifi } from 'lucide-react';
import logo from './assets/afterhours-logo.png';
import './styles.css';

type Product={name:string;description:string;metric:string;price:string;status:string;kind:'sold'|'coming'};
type Purchase={product:string;price:number;date:string};
type PteroData={servers:number;nodes:number;locations:number;online:number;error?:string};
const products:Product[]=[
 {name:'Starter Plan',description:'Basic hosting for one server. Currently sold out.',metric:'472 Hosted servers',price:'$600 USD',status:'Sold out',kind:'sold'},
 {name:'Beta Options',description:'Optional beta features and testing options for upcoming hosting services.',metric:'6 timer Auto-stop',price:'$10–$50 USD',status:'Sold out',kind:'sold'},
 {name:'Servers, Nodes & Locations',description:'New hosting options, nodes and locations are coming soon.',metric:'Coming Availability',price:'$10–$199 USD',status:'Coming soon',kind:'coming'},
 {name:'Premium Access',description:'Premium network access. Availability will be announced later.',metric:'Premium network access',price:'$50 USD',status:'Sold out',kind:'sold'}
];
function App(){
 const [page,setPage]=useState('Oversikt');
 const [unlocked,setUnlocked]=useState(()=>sessionStorage.getItem('afterhours-unlocked')==='1');
 const [code,setCode]=useState(''); const [loginError,setLoginError]=useState('');
 const [purchases,setPurchases]=useState<Purchase[]>(()=>JSON.parse(localStorage.getItem('afterhours-purchases')||'[]'));
 const [ptero,setPtero]=useState<PteroData>({servers:0,nodes:0,locations:0,online:0,error:'Kobler til…'});
 const [showNew,setShowNew]=useState(false); const [newProduct,setNewProduct]=useState('Starter Plan'); const [newPrice,setNewPrice]=useState('600'); const [newDate,setNewDate]=useState(new Date().toISOString().slice(0,10));
 const [toast,setToast]=useState('');
 const unlock=async()=>{const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(code));const h=Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,'0')).join('');if(h==='57440503b005c9e29133a96f13e84fec0ee889520e4608662d455fbfbc36bea3'){sessionStorage.setItem('afterhours-unlocked','1');setUnlocked(true)}else setLoginError('Feil access code')};
 useEffect(()=>{localStorage.setItem('afterhours-purchases',JSON.stringify(purchases))},[purchases]);
 useEffect(()=>{if(!unlocked)return;fetch('/api/pterodactyl.php').then(r=>r.json()).then(setPtero).catch(()=>setPtero(x=>({...x,error:'Backend utilgjengelig'})))},[unlocked]);
 const last30=useMemo(()=>{const since=Date.now()-30*86400000;return purchases.filter(x=>new Date(x.date).getTime()>=since)},[purchases]);
 const earnings=23860+purchases.filter(x=>new Date(x.date).getTime()>=Date.now()-30*86400000).reduce((a,x)=>a+x.price,0);const monthEarnings=47890+purchases.filter(x=>new Date(x.date).getTime()>=Date.now()-30*86400000).reduce((a,x)=>a+x.price,0);const totalEarnings=2903750+purchases.reduce((a,x)=>a+x.price,0);
 const addPurchase=()=>{const n=Number(newPrice.replace(',','.'));if(!newProduct||!Number.isFinite(n))return;setPurchases(x=>[{product:newProduct,price:n,date:newDate},...x]);setShowNew(false);setToast('Nytt kjøp lagret')};
 if(!unlocked)return <div className="loginPage"><div className="loginCard"><img src={logo} alt="Afterhours logo"/><span className="eyebrow">HORII DEVELOPMENTS</span><h1>Afterhours <em>Panel</em></h1><p>Skriv access code for å åpne kontrollpanelet.</p><input autoFocus type="password" inputMode="numeric" placeholder="Access code" value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>e.key==='Enter'&&unlock()}/><button onClick={unlock}>Åpne panel</button>{loginError&&<small className="loginError">{loginError}</small>}</div></div>;
 return <div className="app"><aside><div className="logo"><img className="logoImage" src={logo} alt="Afterhours logo"/><div><b>AFTERHOURS</b><small>Horii Developments</small></div></div><nav>{[['Oversikt',LayoutDashboard],['Servere',Boxes],['Billetter',Ticket],['Inntjening',CircleDollarSign],['Innstillinger',Settings]].map(([n,I])=><button className={page===n?'active':''} onClick={()=>setPage(n as string)} key={n as string}><I size={17}/>{n as string}</button>)}</nav><div className="sideStatus"><span className={ptero.error?'dot warn':'dot'}/>{ptero.error?'Tilkobler Pterodactyl':'Pterodactyl tilkoblet'}<br/><small>panel.afterhoursmc.gg</small></div></aside><main><header><div><p className="eyebrow">CONTROL CENTER / 2026</p><h1>{page}</h1></div><div className="headerActions"><span className={ptero.error?'live warn':'live'}><Wifi size={14}/>{ptero.error||'Live Pterodactyl-data'}</span><button className="icon" title="Logg ut" onClick={()=>{sessionStorage.removeItem('afterhours-unlocked');setUnlocked(false)}}><LogOut size={17}/></button></div></header>{toast&&<div className="toast">{toast}<button onClick={()=>setToast('')}>×</button></div>}
 {page==='Oversikt'&&<><section className="hero"><div><span className="eyebrow">AFTERHOURS / HOSTING</span><h2>Alt du trenger,<br/><em>på ett sted.</em></h2><p>Administrer hosting, servere, kjøp og driftsstatus fra Afterhours Control Center.</p></div><div className="heroOrb"><Server size={42}/><small>LIVE<br/>CONTROL</small></div></section><div className="stats"><article className="stat"><span>Pterodactyl servers</span><strong>{ptero.servers||ptero.error?' '+(ptero.servers||'—'):'—'}</strong></article><article className="stat"><span>Noder</span><strong>{ptero.nodes||'—'}</strong></article><article className="stat"><span>Online players</span><strong>{ptero.online||'—'}</strong></article></div><section className="products"><div className="sectionHead"><div><span className="eyebrow">HOSTING</span><h3>Products</h3></div><button className="primary" onClick={()=>setShowNew(true)}><Plus size={16}/>Nytt kjøp</button></div><div className="productGrid">{products.map(p=><article className="product" key={p.name}><div className="productTop"><span className="productLabel">{p.kind==='sold'?'Hosting':'Hosting'}</span><span className={p.kind==='sold'?'sold':'coming'}>{p.status}</span></div><h3>{p.name}</h3><p>{p.description}</p><div className="productMetric">{p.metric}</div><strong>{p.price}</strong><small>{p.kind==='sold'?'Sold out':'Coming soon'}</small></article>)}</div></section><section className="grid"><article className="panel"><span className="eyebrow">LAST 30 DAYS</span><h3>Inntjening</h3><div className="earnings"><div><small>Denne uken</small><b>23 860 kr</b></div><div><small>Denne måneden</small><b>47 890 kr</b></div><div><small>Totalt registrert</small><b>2 903 750 kr</b></div></div></article><article className="panel"><span className="eyebrow">AFTERHOURS</span><h3>play.afterhoursmc.gg</h3><p className="muted">Hosting og premium access blir oppdatert her når produkter blir tilgjengelige.</p></article></section></>}
 {page==='Servere'&&<article className="panel pagePanel"><span className="eyebrow">PTERODACTYL / LIVE</span><h2>Servers, Nodes & Locations</h2><div className="earnings big"><div><small>Servers</small><b>{ptero.servers||'—'}</b></div><div><small>Nodes</small><b>{ptero.nodes||'—'}</b></div><div><small>Locations</small><b>{ptero.locations||'—'}</b></div></div><p className="muted">Kilde: panel.afterhoursmc.gg. Status oppdateres ved lasting.</p></article>}
 {page==='Billetter'&&<article className="panel pagePanel"><span className="eyebrow">DISCORD / PURCHASES</span><h2>Ticketvarsler</h2><p className="muted">Discord-ticket bridge er ikke koblet til ennå. Kjøpsregistrering gjøres via Nytt kjøp.</p></article>}
 {page==='Inntjening'&&<article className="panel pagePanel"><div className="sectionHead"><div><span className="eyebrow">PURCHASES / LAST 30 DAYS</span><h2>Inntjening</h2></div><button className="primary" onClick={()=>setShowNew(true)}><Plus size={16}/>Nytt kjøp</button></div><div className="earnings big"><div><small>Denne uken</small><b>23 860 kr</b></div><div><small>Denne måneden</small><b>47 890 kr</b></div><div><small>Totalt registrert</small><b>2 903 750 kr</b></div></div><div className="purchaseList">{last30.length?last30.map((p,i)=><div key={i}><span>{p.product}<small>{p.date}</small></span><b>{p.price.toFixed(2)} kr</b></div>):<p className="muted">Ingen kjøp i siste 30 dager.</p>}</div></article>}
 {page==='Innstillinger'&&<article className="panel pagePanel"><span className="eyebrow">INTEGRATION STATUS</span><h2>Pterodactyl</h2><div className="notice"><Wifi size={18}/> {ptero.error||'Tilkoblet til panel.afterhoursmc.gg'}</div><p className="muted">API-koblingen kjører server-side. Ingen Pterodactyl-token ligger i nettleseren eller GitHub.</p></article>}
 </main>{showNew&&<div className="modalBack"><div className="modal"><div className="sectionHead"><h3>Nytt kjøp</h3><button className="icon" onClick={()=>setShowNew(false)}>×</button></div><label>Produkt<select value={newProduct} onChange={e=>setNewProduct(e.target.value)}>{products.map(p=><option key={p.name}>{p.name}</option>)}</select></label><label>Beløp USD<input value={newPrice} onChange={e=>setNewPrice(e.target.value)} inputMode="decimal"/></label><label>Dato<input type="date" value={newDate} onChange={e=>setNewDate(e.target.value)}/></label><button className="primary" onClick={addPurchase}>Lagre kjøp</button></div></div>}</div>;
}
export default App;
