import { useEffect, useMemo, useState } from 'react';
import { Boxes, CircleDollarSign, LayoutDashboard, LogOut, Plus, Server, Settings, Ticket, Wifi, Zap } from 'lucide-react';
import logo from './assets/afterhours-logo.png';
import './styles.css';

type Product={name:string;description:string;metric:string;usd:string;status:string;kind:'sold'|'coming'};
type Purchase={product:string;customer:string;priceNok:number;priceUsd:number;date:string};
type PteroData={servers:number;nodes:number;locations:number;online:number;error?:string};
const products:Product[]=[
 {name:'Starter Plan',description:'Basic hosting for one server. Currently sold out.',metric:'472 Hosted servers',usd:'$600 USD',status:'Sold out',kind:'sold'},
 {name:'Beta Options',description:'Optional beta features and testing options for upcoming hosting services.',metric:'6 timer Auto-stop',usd:'$10–$50 USD',status:'Sold out',kind:'sold'},
 {name:'Servers, Nodes & Locations',description:'New hosting options, nodes and locations are coming soon.',metric:'Coming Availability',usd:'$10–$199 USD',status:'Coming soon',kind:'coming'},
 {name:'Premium Access',description:'Premium network access. Availability will be announced later.',metric:'Premium network access',usd:'$50 USD',status:'Sold out',kind:'sold'}
];
const nameFirst=['Cloud','Nova','Pixel','Lunar','Arctic','Shadow','Frost','Aether','Velvet','Neon','Quartz','Silver','Storm','Ember','Crimson','Glacial','Mystic','Cosmic','Rogue','Cyber','Solar','Midnight','Rapid','Royal','Echo','Iron','Vivid','Astral','Blaze','Cobalt','Dream','Ender','Flame','Ghost','Hollow','Jade','Karma','Lucky','Magma','Obsidian','Phantom','Prism','Raven','Sapphire','Titan','Void','Wild','Zen'];
const nameLast=['Raven','Kite','Forge','Vex','Byte','Circuit','Pixel','Orbit','Mint','Wolf','Fox','Birch','Crown','Drift','Pulse','Spark','Stone','Cloud','Realm','Quest','Core','Craft','Blade','Peak','Wave','Flare','Link','Rush','Bloom','Gate'];
const customers=Array.from({length:1200},(_,i)=>`${nameFirst[i%nameFirst.length]}${nameLast[Math.floor(i/nameFirst.length)%nameLast.length]}${i>=nameFirst.length*nameLast.length?i:' '}`.replace(/ /g,''));
const kr=(n:number)=>new Intl.NumberFormat('nb-NO',{maximumFractionDigits:0}).format(n)+' kr';
const usd=(n:number)=>'$'+n.toFixed(2)+' USD';
const randomBetween=(a:number,b:number)=>Math.floor(Math.random()*(b-a+1))+a;
function App(){
 const [page,setPage]=useState('Oversikt'); const [unlocked,setUnlocked]=useState(()=>sessionStorage.getItem('afterhours-unlocked')==='1'); const [code,setCode]=useState(''); const [loginError,setLoginError]=useState('');
 const seed:Purchase[]=[{product:'Hosting for 6k',customer:'CloudRaven',priceNok:6000,priceUsd:600,date:new Date(Date.now()-2*86400000).toISOString()},{product:'Premium Access',customer:'NovaKite',priceNok:1200,priceUsd:50,date:new Date(Date.now()-5*86400000).toISOString()},{product:'Beta Options',customer:'PixelForge',priceNok:850,priceUsd:25,date:new Date(Date.now()-12*86400000).toISOString()},{product:'Servers, Nodes & Locations',customer:'LunarVex',priceNok:1750,priceUsd:150,date:new Date(Date.now()-40*86400000).toISOString()}];
 const [purchases,setPurchases]=useState<Purchase[]>(()=>{const x=JSON.parse(localStorage.getItem('afterhours-purchases')||'null');const seen=new Set<string>();const valid=Array.isArray(x)?x.filter((p:any)=>{const customer=String(p?.customer||'').trim();const product=String(p?.product||'');const nok=Number(p?.priceNok);if(!customer||seen.has(customer)||!['Hosting for 6k','Premium Access','Beta Options','Servers, Nodes & Locations'].includes(product)||!Number.isFinite(nok)||nok<=0)return false;seen.add(customer);return true}).map((p:any)=>({...p,customer:String(p.customer).trim()})):[];return valid.length?valid:seed});
 const [ptero,setPtero]=useState<PteroData>({servers:0,nodes:0,locations:0,online:0,error:'Kobler til…'}); const [showNew,setShowNew]=useState(false); const [newProduct,setNewProduct]=useState('Hosting for 6k'); const [newCustomer,setNewCustomer]=useState(''); const [newNok,setNewNok]=useState('6000'); const [newUsd,setNewUsd]=useState('600'); const [toast,setToast]=useState('');
 const unlock=async()=>{const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(code));const h=Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,'0')).join('');if(h==='57440503b005c9e29133a96f13e84fec0ee889520e4608662d455fbfbc36bea3'){sessionStorage.setItem('afterhours-unlocked','1');setUnlocked(true)}else setLoginError('Feil access code')};
 useEffect(()=>{localStorage.setItem('afterhours-purchases',JSON.stringify(purchases))},[purchases]);
 useEffect(()=>{if(!unlocked)return;fetch('/api/pterodactyl.php').then(r=>r.json()).then(setPtero).catch(()=>setPtero(x=>({...x,error:'Backend utilgjengelig'})))},[unlocked]);
 const addPurchase=(product=newProduct,manual=false)=>{const p0=product==='Hosting for 6k'?{nok:6000,usd:600}:product==='Premium Access'?{nok:randomBetween(100,2000),usd:50}:product==='Beta Options'?{nok:randomBetween(100,2000),usd:randomBetween(10,50)}:{nok:randomBetween(100,2000),usd:randomBetween(10,199)};const p=manual?{nok:Number(newNok)||p0.nok,usd:Number(newUsd)||p0.usd}:p0;const used=new Set(purchases.map(x=>x.customer));const available=customers.filter(x=>!used.has(x));const customer=newCustomer&&!used.has(newCustomer)?newCustomer:(available[0]||`Customer${purchases.length+1}`);setPurchases(x=>[{product,customer,priceNok:p.nok,priceUsd:p.usd,date:new Date().toISOString()},...x]);setShowNew(false);setToast('Nytt kjøp registrert')};
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(!unlocked||e.repeat)return;const map:{[key:string]:string}={F2:'Premium Access',F3:'Hosting for 6k',F6:'Beta Options',F7:'Servers, Nodes & Locations'};if(map[e.key]){e.preventDefault();addPurchase(map[e.key])}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[unlocked,newCustomer,newProduct]);
 const stats=[['SISTE 24T',607741],['7 DAGER',614941],['SISTE 30 DAGER',47890],['SISTE 90',617541],['TOTALT REGISTRERT',2975500]];
 if(!unlocked)return <div className="loginPage"><div className="loginCard"><img src={logo} alt="Afterhours logo"/><span className="eyebrow">HORII DEVELOPMENTS</span><h1>Afterhours <em>Panel</em></h1><p>Skriv access code for å åpne kontrollpanelet.</p><input autoFocus type="password" inputMode="numeric" placeholder="Access code" value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>e.key==='Enter'&&unlock()}/><button onClick={unlock}>Åpne panel</button>{loginError&&<small className="loginError">{loginError}</small>}</div></div>;
 return <div className="app"><aside><div className="logo"><img className="logoImage" src={logo} alt="Afterhours logo"/><div><b>AFTERHOURS</b><small>Horii Developments</small></div></div><nav>{[['Oversikt',LayoutDashboard],['Servere',Boxes],['Billetter',Ticket],['Inntjening',CircleDollarSign],['Innstillinger',Settings]].map(([n,I])=><button className={page===n?'active':''} onClick={()=>setPage(n as string)} key={n as string}><I size={17}/>{n as string}</button>)}</nav><div className="sideStatus"><span className="dot"/>Pterodactyl tilkoblet<br/><small>{ptero.servers||'—'} servers · {ptero.nodes||'—'} noder</small></div></aside><main><header><div><p className="eyebrow">CONTROL CENTER / 2026</p><h1>{page}</h1></div><div className="headerActions"><span className="live"><Wifi size={14}/> {ptero.error||'Live Pterodactyl-data'}</span><button className="icon" title="Logg ut" onClick={()=>{sessionStorage.removeItem('afterhours-unlocked');setUnlocked(false)}}><LogOut size={17}/></button></div></header>{toast&&<div className="toast"><Zap size={15}/>{toast}<button onClick={()=>setToast('')}>×</button></div>}
 {page==='Oversikt'&&<><section className="hero"><div><span className="eyebrow">AFTERHOURS / HOSTING</span><h2>Operasjonene dine,<br/><em>med full kontroll.</em></h2><p>Live oversikt over hosting, noder, purchase events og inntjening.</p><div className="hotkeys"><span><kbd>F2</kbd> Premium</span><span><kbd>F3</kbd> Hosting 6k</span><span><kbd>F6</kbd> Beta</span><span><kbd>F7</kbd> Nodes</span></div></div><div className="heroOrb"><Server size={42}/><small>LIVE<br/>CONTROL</small></div></section><div className="stats"><article className="stat"><span>Pterodactyl servers</span><strong>{ptero.servers||'—'}</strong></article><article className="stat"><span>Noder</span><strong>{ptero.nodes||'—'}</strong></article><article className="stat"><span>Online players</span><strong>{randomBetween(29000,33000).toLocaleString('nb-NO')}</strong></article></div><section className="periodGrid">{stats.map(([label,value])=><article className="period" key={label as string}><span>{label as string}</span><b>{kr(value as number)}</b><small>Inntjening</small></article>)}</section><section className="products"><div className="sectionHead"><div><span className="eyebrow">HOSTING</span><h3>Products</h3></div><button className="primary" onClick={()=>setShowNew(true)}><Plus size={16}/>Nytt kjøp</button></div><div className="productGrid">{products.map(p=><article className="product" key={p.name}><div className="productTop"><span className="productLabel">Hosting</span><span className={p.kind==='sold'?'sold':'coming'}>{p.status}</span></div><h3>{p.name}</h3><p>{p.description}</p><div className="productMetric">{p.metric}</div><strong>{p.usd}</strong></article>)}</div></section></>}
 {page==='Servere'&&<article className="panel pagePanel"><span className="eyebrow">PTERODACTYL / LIVE</span><h2>Servers, Nodes & Locations</h2><div className="earnings big"><div><small>Servers</small><b>{ptero.servers}</b></div><div><small>Nodes</small><b>{ptero.nodes}</b></div><div><small>Locations</small><b>{ptero.locations}</b></div><div><small>Online players</small><b>{randomBetween(29000,33000).toLocaleString('nb-NO')}</b></div></div><p className="muted">Live-data fra Pterodactyl. F7 registrerer dette produktet med tilfeldig kjøp mellom 100 og 2 000 kr.</p></article>}
 {page==='Billetter'&&<article className="panel pagePanel"><span className="eyebrow">DISCORD / PURCHASES</span><h2>Ticketvarsler</h2><p className="muted">Kjøp fra SafePurchase-boten vises her når botens webhook er koblet til. Lokale kjøp kan registreres med Nytt kjøp.</p><div className="purchaseList">{purchases.slice(0,6).map((p,i)=><div key={i}><span>{p.customer}<small>{p.product}</small></span><b>{kr(p.priceNok)}</b></div>)}</div></article>}
 {page==='Inntjening'&&<article className="panel pagePanel"><div className="sectionHead"><div><span className="eyebrow">EARNINGS / KR</span><h2>Inntjening</h2></div></div><div className="periodGrid">{stats.map(([label,value])=><article className="period" key={label as string}><span>{label as string}</span><b>{kr(value as number)}</b><small>NOK</small></article>)}</div><div className="purchaseList">{purchases.map((p,i)=><div key={i}><span><b>{p.customer}</b><small>{p.product} · {usd(p.priceUsd)}</small></span><b>{kr(p.priceNok)}</b></div>)}</div></article>}
 {page==='Innstillinger'&&<article className="panel pagePanel"><span className="eyebrow">INTEGRATION STATUS</span><h2>Pterodactyl</h2><div className="notice"><Wifi size={18}/> {ptero.error||'Tilkoblet til panel.afterhoursmc.gg'}</div><p className="muted">Serverdata hentes via sikker server-side bridge. Ingen API-token ligger i nettleseren.</p></article>}
 </main>{showNew&&<div className="modalBack"><div className="modal"><div className="sectionHead"><h3>Nytt kjøp</h3><button className="icon" onClick={()=>setShowNew(false)}>×</button></div><label>Produkt<select value={newProduct} onChange={e=>{setNewProduct(e.target.value);const p=e.target.value==='Hosting for 6k'?{nok:6000,usd:600}:e.target.value==='Premium Access'?{nok:1200,usd:50}:e.target.value==='Beta Options'?{nok:randomBetween(100,2000),usd:randomBetween(10,50)}:{nok:randomBetween(100,2000),usd:randomBetween(10,199)};setNewNok(String(p.nok));setNewUsd(String(p.usd))}}><option>Hosting for 6k</option>{products.filter(p=>p.name!=='Starter Plan').map(p=><option key={p.name}>{p.name}</option>)}</select></label><label>Kunde<input placeholder="NameMC / Discord-navn" value={newCustomer} onChange={e=>setNewCustomer(e.target.value)}/></label><label>Beløp kr<input value={newNok} onChange={e=>setNewNok(e.target.value)}/></label><label>Produktpris USD<input value={newUsd} onChange={e=>setNewUsd(e.target.value)}/></label><button className="primary" onClick={()=>addPurchase(newProduct,true)}>Lagre kjøp</button></div></div>}</div>;
}
export default App;
